name: Schedule Bot Check

on:
  schedule:
    # This runs every 10 minutes, adjust as needed
    - cron: '*/10 * * * *'

jobs:
  call-vercel-endpoint:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Vercel Bot Check
      run: |
        curl -X GET https://discord-codewars-bot.vercel.app/check
